package restly.exceptions.servererror;

import restly.*;

/**
 * 511 Network Authentication Required
 * <p/>
 * <p>
 * The 511 status code indicates that the client needs to authenticate
 * to gain network access.
 * </p>
 * <p>
 * The response representation SHOULD contain a link to a resource that
 * allows the user to submit credentials (e.g., with an HTML form).
 * </p>
 * <p>
 * Note that the 511 response SHOULD NOT contain a challenge or the
 * login interface itself, because browsers would show the login
 * interface as being associated with the originally requested URL,
 * which may cause confusion.
 * </p>
 * <p>
 * The 511 status SHOULD NOT be generated by origin servers; it is
 * intended for use by intercepting proxies that are interposed as a
 * means of controlling access to the network.
 * </p>
 * <p>
 * Responses with the 511 status code MUST NOT be stored by a cache.
 * </p>
 *
 * @author <a href="http://restly.org/">Erik Beeson</a>
 */
public class NetworkAuthenticationRequiredException extends HttpServerErrorException {
	public static final HttpStatus HTTP_STATUS = HttpStatus.NETWORK_AUTHENTICATION_REQUIRED;

	public NetworkAuthenticationRequiredException() {
		this(null);
	}

	public NetworkAuthenticationRequiredException(Object data) {
		super(HTTP_STATUS, data);
	}
}